default_stages: [pre-commit]
fail_fast: true

ci:
  autoupdate_schedule: weekly
  skip: [no-commit-to-branch]
  submodules: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: name-tests-test
    args: [--pytest-test-first]
    types: [python]
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args: [--line-length=120]
    types: [python]

- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [--profile=black]
    types: [python]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
  - id: pyupgrade
    args: [--py311-plus]
    types: [python]

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [--max-line-length=120]
    types: [python]
